#! /bin/bash
testuser=xyghjd
if grep $testuser /etc/passwd
then
	echo "The bash files for user $testuser"
	ls -a /home/$testuser/.b*
elif grep adesh /etc/passwd
then
	echo "There is no user name $testuser"
	echo "There is adesh as a user name"
fi
