#!/bin/bash
#mis-using string comparision
val1=baseball
val2=hockey
if [ $val1 \> $val2 ] # check the sum of ASCI values
then 
	echo "$val1 is greater than $val2"
else
	echo "$val1 is less than $val2"
fi

