#! /bin/bash
# diffrence between $* and $@
count=1
for param in "$*"
do 
	echo "\$* Parameter #$count = $param"
	count=$[ $count +1 ]
done
count=1
for param in "$@"
do 
	echo "\$@ Parameter #$count = $param"
	count=$[ $count +1 ]
done
# $* variable treated all parameter as single word 
# $@ variable treates each parameter saparately
