#! /bin/bash
#extarcting option and parameters
while [ -n "$1" ]
do 
	case "$1" in
		-a) echo "Found the $1 option";;
		-b) echo "Found the $1 option";;
		-c) echo "Found the $1 option";;
		--)shift
		break;;
		*) echo "$1 is not an option";;
	esac
	shift
done
count=1
for param in $@
do
	echo "parameter $count: $param"
	count=$[ $count + 1 ]
done

